# Generated by Django 3.1.6 on 2021-04-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210407_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/images/'),
        ),
    ]
