# Generated by Django 3.1.6 on 2021-04-08 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210408_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
